# Generated by Django 3.1.6 on 2021-04-07 13:29

import audioFile.models
import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('narrator', models.CharField(max_length=100)),
                ('duration', models.PositiveBigIntegerField()),
                ('uploaded_time', models.DateTimeField(default=datetime.datetime(2021, 4, 7, 13, 29, 14, 730417, tzinfo=utc), validators=[audioFile.models.date_validator])),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.PositiveBigIntegerField()),
                ('uploaded_time', models.DateTimeField(default=datetime.datetime(2021, 4, 7, 13, 29, 14, 729213, tzinfo=utc), validators=[audioFile.models.date_validator])),
                ('host', models.CharField(max_length=100)),
                ('participants', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=10)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.PositiveBigIntegerField()),
                ('uploaded_time', models.DateTimeField(default=datetime.datetime(2021, 4, 7, 13, 29, 14, 542272, tzinfo=utc), validators=[audioFile.models.date_validator])),
            ],
        ),
    ]
