# Generated by Django 3.1.6 on 2021-04-10 06:59

import audioFile.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('audioFile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='uploaded_time',
            field=models.DateTimeField(validators=[audioFile.models.date_validator], verbose_name=datetime.datetime(2021, 4, 10, 6, 59, 54, 605888, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='uploaded_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 10, 6, 59, 54, 604694, tzinfo=utc), validators=[audioFile.models.date_validator]),
        ),
        migrations.AlterField(
            model_name='song',
            name='uploaded_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 10, 6, 59, 54, 415357, tzinfo=utc), validators=[audioFile.models.date_validator]),
        ),
    ]
