# Generated by Django 3.1.6 on 2021-04-10 09:20

import audioFile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioFile', '0002_auto_20210410_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='uploaded_time',
            field=models.DateTimeField(auto_now_add=True, validators=[audioFile.models.date_validator]),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='uploaded_time',
            field=models.DateTimeField(auto_now_add=True, validators=[audioFile.models.date_validator]),
        ),
        migrations.AlterField(
            model_name='song',
            name='uploaded_time',
            field=models.DateTimeField(auto_now_add=True, validators=[audioFile.models.date_validator]),
        ),
    ]
